### 1. Try to Login (Should FAIL - User doesn't exist yet)
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "coolAdmin",
    "password": "securePass123"
}

### 2. Register a new User (NEW!)
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "coolAdmin",
    "password": "securePass123"
}

### 3. Login with that new User (Should WORK)
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "coolAdmin",
    "password": "securePass123"
}

### 4. Add a book (Proof that you are logged in)
POST http://localhost:3000/books
Content-Type: application/json

{
    "title": "Harry Potter",
    "author": "J.K. Rowling"
}

### 5. Logout
POST http://localhost:3000/logout

### 6. Try to delete again (SHOULD FAIL)
DELETE http://localhost:3000/books/2